### ISSUE TITLE
Unable to restore-db

### ISSUE THREAD

**Issue by kosecki123** [Datomic/mbrainz-sample#10]
When trying to restore-db on OS X 10.11.6 with datomic-free-0.9.5390

`bin/datomic restore-db file:///Users/piotrkosinski/Projects/mbrainz-1968-1973 datomic:free://localhost:4334/mbrainz-1968-1973`

got this error

```
java.lang.NumberFormatException: For input string: ".DS_Store"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:578)
	at java.lang.Long.parseLong(Long.java:631)
	at datomic.backup$describe_backups$fn__9012.invoke(backup.clj:531)
	at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$mapv.invokeStatic(core.clj:6618)
	at clojure.core$mapv.invoke(core.clj:6618)
	at datomic.backup$describe_backups.invokeStatic(backup.clj:531)
	at datomic.backup$describe_backups.invoke(backup.clj:522)
	at datomic.backup$latest_t.invokeStatic(backup.clj:627)
	at datomic.backup$latest_t.invoke(backup.clj:625)
	at datomic.backup$require_latest_t.invokeStatic(backup.clj:632)
	at datomic.backup$require_latest_t.invoke(backup.clj:630)
	at datomic.backup_cli$restore.invokeStatic(backup_cli.clj:51)
	at datomic.backup_cli$restore.invoke(backup_cli.clj:43)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at datomic.require$require_and_run.invokeStatic(require.clj:22)
	at datomic.require$require_and_run.doInvoke(require.clj:17)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at datomic$_main$fn__28.invoke(datomic.clj:150)
	at datomic$_main.invokeStatic(datomic.clj:149)
	at datomic$_main.doInvoke(datomic.clj:142)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.main$main_opt.invokeStatic(main.clj:314)
	at clojure.main$main_opt.invoke(main.clj:310)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:186)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

Removing .DS_Store file from Projects/mbrainz-1968-1973 folder doesn't fix the problem.

**Comment by stuarthalloway** [comment]
Remove .DS_Store from roots/
