### ISSUE TITLE
Import fails on OS X with Datomic free 0.9.5173

### ISSUE THREAD

**Issue by heim** [Datomic/mbrainz-sample#6]
Importing the mbrainz-file fails with following stacktrace: 
````
Caused by: java.io.FileNotFoundException: Could not locate datomic/process_monitor__init.class or datomic/process_monitor.clj on classpath:
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at datomic.backup_cli$loading__4958__auto__.invoke(backup_cli.clj:1)
	at datomic.backup_cli__init.load(Unknown Source)
	at datomic.backup_cli__init.<clinit>(Unknown Source)
	... 34 more
```

It works with datomic free 0.9.5153.

**Comment by benkamphaus** [comment]
Hi @heim, we've reproduced and identified the cause of this issue, which is a deficiency in 0.9.5173 (free only) backup/restore. Free users should stay on 0.9.5153, or, if appropriate for their use case, use 0.9.5173 Pro Starter (the deficiency does not exist in Pro). I'll update you when a release correcting this deficiency is out.

**Comment by heim** [comment]
:+1:

**Comment by benkamphaus** [comment]
Hi @heim ,

Letting you know the [latest datomic release](https://groups.google.com/forum/#!topic/datomic/IGzjBbHr10E) corrects the free backup/restore issue.

Best,
Ben

**Comment by heim** [comment]
Thanks guys!
